### ISSUE TITLE
An explanation of cluster method parameters

### ISSUE THREAD

**Issue by papakonstantinouko** [gjergjie/Server-Side-Google-Map-Markers-Clustering-C-plus-plus-V8#1]
Hello, I would like to use your c++ clustering solution to my .net project. I cannot read c++ so I would like to ask you for an explanation of the parameters in the cluster method. As I see in this example 

myAddon.cluster(ArrayCoordinates, 20, 10, 10)

ArrayCoordinates would be an array of doubles with lon/lat values?
The second parameter, distance, can you please elaborate on it? Is this in pixels?

And finally what would this method return to the caller?

**Comment by gjergjie** [comment]
Hello, 

The params are: 
1. The array with coordinates, Array should be something like Array(Array(location =&gt; [lat, lng]), Array(location =&gt; [lat, lng]), ...)
2. Distance between points to create the cluster 
3. Zoom level 
4. Limit cluster creation, for instance we don’t want to create clusters with 2 or 4 points, so we put the integer 5 or 6 or 20, whatever, so cluster would be created when enough points are near each other based on this limit you set

---- On Mon, 13 Jun 2016 12:02:33 +0000 Konstantinos &lt;notifications@github.com&gt;wrote ---- 

Hello, I would like to use your c++ clustering solution to my .net project. I cannot read c++ so I would like to ask you for an explanation of the parameters in the cluster method. As I see in this example 

myAddon.cluster(ArrayCoordinates, 20, 10, 10)

ArrayCoordinates would be an array of doubles with lon/lat values?

 What do the 3 other parameters mean please?
